# Generated by Django 4.1.2 on 2022-11-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_student_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_complaint_details',
            name='regno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admin_outpass_details',
            name='regno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint_details',
            name='regno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='outpass_details',
            name='regno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student_details',
            name='regno',
            field=models.CharField(default='', max_length=100),
        ),
    ]
